name: PROD CI/CD
on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'
  # release:
  #   types: [published]
  workflow_dispatch:

    
jobs: 
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test console
        run: |
          # 查看当前目录和package.json文件
          ls -al
          cat package.json
          echo "test console"