# 监听带有hotfix label的pr合并到develop
name: release hotfix
on:
  pull_request:
    ## 修改label或者提交代码都会触发
    types: [closed]
    branches:
      - 'develop'

permissions:
  contents: write
  pull-requests: write
  
jobs: 
  hotfix:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.RICARDO_TOKEN }}
          release-type: node
          include-component-in-tag: true