name: auto-release

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          token: ${{ secrets.RICARDO_TOKEN }}
          release-type: node
          package-name: Fortress-Demo
          include-v-in-tag: false
          default-branch: develop
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"ci","section":"Miscellaneous","hidden":false},{"type":"perf","section":"Miscellaneous","hidden":false}]'
      
      
      - name: checkout to main
        uses: actions/checkout@v4
        if: ${{ steps.release-please.outputs.release_created }}
        with:
          ref: main 
          
      - name: Merge tag to main
        if: ${{ steps.release-please.outputs.release_created }}
        run: |
          git fetch --tags
          ls -al
          cat package.json
          git merge refs/tags/${{ steps.release-please.outputs.tag_name }}
          git push

      - name: Reset uat to master
        if: ${{ steps.release-please.outputs.release_created }}
        run: |
          git fetch --tags
          git checkout origin/uat-sg
          git reset --hard origin/master
          git push -f
          git checkout origin/uat-us
          git reset --hard origin/master
          git push -f
          git checkout origin/uat-au
          git reset --hard origin/master
          git push -f
