name: auto-release

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: node
          package-name: Fortress-Demo
          include-v-in-tag: false
          default-branch: develop
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"ci","section":"Miscellaneous","hidden":false},{"type":"perf","section":"Miscellaneous","hidden":false}]'
      # 将tag: steps.release.outputs.tag_name 合并到 master 分支
      # test commit
      - name: Merge tag to master
        if: ${{ steps.release-please.outputs.release_created }}
        run: |
          TAG_NAME="${{ steps.release-please.outputs.tag_name }}"
          git checkout main

          if git merge "refs/tags/${TAG_NAME}"; then
            git push
          else
            echo "Merge failed for tag '${TAG_NAME}'. Please resolve the issue."
            exit 1
          fi