on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-hotfix

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: Fortress-Demo
          include-v-in-tag: false
          changelog-types: '[{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"ci","section":"Miscellaneous","hidden":false},{"type":"perf","section":"Miscellaneous","hidden":false}]'
