# 监听带有hotfix label的pr合并到develop
name: hotfix
on:
  pull_request:
    types: [labeled]
    branches:
      - 'develop'

jobs: 
  hotfix:
    if: contains(github.event.pull_request.labels.*.name, 'hotfix')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 针对pr的代码进行checkout
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Display branch information
        run: |
          echo "The branch of the pull request is: ${{ github.event.pull_request.head.ref }}"
          echo "labels: ${{ contains(github.event.pull_request.labels.*.name, 'hotfix') }}"

      - name: Cat file
        run: cat README.md
      
      - name: Trigger prod.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.RICARDO_TOKEN }}
        run: |
          gh workflow run prod.yaml -f branch=${{ github.event.pull_request.head.ref }}